language: python
python: '3.6'
env: LC_ALL=C.UTF-8 LANG=C.UTF-8
install:
- pip install poetry
- poetry lock
- poetry install
script:
- poetry run coverage run --source pype --module pytest
before_deploy:
- poetry build
deploy:
  provider: script
  script: poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
  on:
    tags: true
    branches:
      only:
        - master
