language: python
python: '3.6'
install:
- pip install poetry
- poetry install
script:
- poetry run coverage run --source pype --module pytest
before_deploy:
- poetry build
deploy:
  provider: script
  script: poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
  on:
    tags: false
    branches:
      only:
        - master
