dist: xenial
language: python
python: '3.7'
env: LC_ALL=C.UTF-8 LANG=C.UTF-8
install:
- pycli init
- pycli lock
- pycli init
script:
- tox -e coverage
deploy:
  provider: script
  script: pycli upload
  on:
    tags: true
    branches:
      only:
        - master
