dist: xenial
language: python
python: '3.7'
env: LC_ALL=C.UTF-8 LANG=C.UTF-8
install:
- pip install poetry
- poetry lock
- poetry install
script:
- tox
before_deploy:
- poetry build
- poetry run twine check dist/*
deploy:
  provider: script
  script: poetry publish --build --username $PYPI_USERNAME --password $PYPI_PASSWORD
  on:
    tags: true
    branches:
      only:
        - master
