dist: xenial
language: python
python: '3.7'
env: LC_ALL=C.UTF-8 LANG=C.UTF-8
install:
- ./pycli init
- pip install tox
script:
- tox -e coverage
- tox -e check
- tox -e codecov
deploy:
  provider: script
  script: ./pycli clean && ./pycli init && ./pycli build &&./pycli upload
  on:
    tags: true
    branches:
      only:
        - master
