[tool.poetry]
name = "python-pype"
version = "0.0.55"
description = ""
authors = ["author <author@example.com>"]
readme = "README.rst"
packages = [
         {include = "pype"}
]

[tool.poetry.dependencies]
python = "^3.6"

click = "*"
toolz = "*"
attrs = "*"
click-default-group = "*"
parso = "*"
twisted = "*"
bump2version = "^0.5.10"
trio = "^0.11.0"
trio-typing = "^0.2.0"


[tool.poetry.dev-dependencies]
"flake8" = "*"
bump2version = "*"
coverage = "*"
hypothesis = "*"
pylint = "*"
pytest = "*"
requests = "*"
aiohttp = "*"
jedi = "*"
"autopep8" = "*"
yapf = "*"
parso = "*"
twine = "*"
vulture = "*"
treq = "*"
poetry = "*"
vprof = "^0.37.6"
mypy = "^0.700.0"



[tool.poetry.scripts]

pype = 'pype:app.cli'
